# streamlit_app/.streamlit/secrets.toml
MONGO_URI = "mongodb+srv://muambamvelejules_db_user:fLWyNBIoeBZs0lh4@cluster0.y22tbbi.mongodb.net/?appName=Cluster0"
MONGO_DB = "ind320"
MONGO_COLL = "production_mba_hour"
